name: deploy-container

on:
  push:
    branches:
      - main
      - master
# removed the Paths option

defaults:
  run:
    working-directory: container

jobs:
  build:
    name: Running Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/chectout@v2
      - uses: actions/setup-node@v2
          with:
            node-version: '14'
      - name: Install
      - run: npm install
      - name: Build
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - name: Connect to AWS
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
